### ISSUE TITLE
Unsupported Attribute on Server.Send

### ISSUE THREAD

**Issue by JamesrenaudMitel** [reklatsmasters/stun#2]
Using the supplied example code, with my STUN server from https://github.com/jselbie/stunserver I get an exception on the Send() method.

My code is:
var stun = require('stun')
const { STUN_BINDING_REQUEST, STUN_ATTR_XOR_MAPPED_ADDRESS } = stun.constants

const server = stun.createServer()
const request = stun.createMessage(STUN_BINDING_REQUEST)

server.once('bindingResponse', stunMsg => {
  console.log('your ip:', stunMsg.getAttribute(STUN_ATTR_XOR_MAPPED_ADDRESS).value.address)

  server.close()
})

server.send(request, 3478, 'stun.mitel.io')

And the stack trace I get out is
`Exception has occurred: Error
Error: Unsupported attribute type "32811".
    at parseAttribute (c:\github\devops-udp-healthcheck\node_modules\stun\lib\message.js:289:9)
    at stunMsg._attrs.packet.attributes.map.attrPacket (c:\github\devops-udp-healthcheck\node_modules\stun\lib\message.js:69:7)
    at Array.map (native)
    at Function.from (c:\github\devops-udp-healthcheck\node_modules\stun\lib\message.js:68:40)
    at StunServer.process (c:\github\devops-udp-healthcheck\node_modules\stun\lib\server.js:31:33)
    at StunServer.handleMessage (c:\github\devops-udp-healthcheck\node_modules\stun\lib\server.js:61:10)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)`

I'm at a bit of a loss. This seems to work fine with the supplied Google STUN servers, and in theory the STUNTMAN STUN server should be following all the appropriate RFC's.

Any guidance would be much appreciated.

**Comment by reklatsmasters** [comment]
It seems that `stun.mitel.io` sends optional (32811 -> 0x802b) attribute (non-standart may be). According to RFC the stun server should ignore unknown optional attribute. I forgot to implement this :pensive:.

**Comment by JamesrenaudMitel** [comment]
It looks like 0x802b per RFC 5780 is RESPONSE-ORIGIN.

**Comment by reklatsmasters** [comment]
Ok, I will add RFC5780 too.  I used webrtc stun server as example https://chromium.googlesource.com/external/webrtc/+/master/webrtc/p2p/base/stun.h.

**Comment by reklatsmasters** [comment]
@JamesrenaudMitel I fixed this issue. If you want to support RFC5780, create a separate issue please.
